@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package moze_intel.projecte.expansion.block.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;