@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package moze_intel.projecte.expansion.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;