@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package moze_intel.projecte.expansion.integrations.curios;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;